import { readdirSync, statSync, existsSync, writeFileSync } from 'fs';
import { join } from 'path';

const componentsDir = './src/components';
const indexPath = './src/index.ts';

const dirs = readdirSync(componentsDir)
  .filter(name => {
    const fullPath = join(componentsDir, name);
    if (!statSync(fullPath).isDirectory()) return false;

    // Verifica se tem o arquivo principal .tsx
    const tsxFile = join(fullPath, `${name}.tsx`);
    return existsSync(tsxFile);
  });

const lines = [
  '"use client";',
  '',
  '// Auto-generated by scripts/generate-index.mjs',
  '// NÃO edite manualmente — rode npm run build para regenerar',
  '',
  ...dirs.map(name => `export { ${name} } from './components/${name}';`),
  '',
];

writeFileSync(indexPath, lines.join('\n'));
console.log(`✅ src/index.ts gerado com ${dirs.length} componentes:`);
dirs.forEach(name => console.log(`   - ${name}`));
