// scripts/sync-skill.mjs
import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'fs';
import { join } from 'path';

const COMPONENTS_DIR = './src/components';
const SKILL_DIR = './.claude/skills/olist-ds-skill';
const VARIABLES_PATH = './src/generated/variables.css';

// ─── 1. Atualiza COMPONENTS.md ────────────────────────────

function syncComponents() {
  const dirs = readdirSync(COMPONENTS_DIR)
    .filter(name => {
      const fullPath = join(COMPONENTS_DIR, name);
      if (!statSync(fullPath).isDirectory()) return false;
      return existsSync(join(fullPath, `${name}.tsx`));
    });

  const components = dirs.map(name => {
    const tsxPath = join(COMPONENTS_DIR, name, `${name}.tsx`);
    const cssPath = join(COMPONENTS_DIR, name, `${name}.module.css`);
    const source = readFileSync(tsxPath, 'utf-8');

    // Extrai interface de props
    const propsMatch = source.match(/interface\s+(\w+Props)\s*\{([^}]+)\}/s);
    const propsBlock = propsMatch ? propsMatch[0] : 'Props não encontradas';

    // Extrai variantes de props (ex: 'primary' | 'secondary')
    const variants = [];
    const variantMatches = source.matchAll(/'([^']+)'/g);
    for (const m of variantMatches) {
      if (!variants.includes(m[1]) && m[1].length < 30) {
        variants.push(m[1]);
      }
    }

    // Verifica quais arquivos existem
    const hasTest = existsSync(join(COMPONENTS_DIR, name, `${name}.test.tsx`));
    const hasStory = existsSync(join(COMPONENTS_DIR, name, `${name}.stories.tsx`));
    const hasCss = existsSync(cssPath);

    // Extrai tokens CSS usados
    let tokensUsed = [];
    if (hasCss) {
      const css = readFileSync(cssPath, 'utf-8');
      const tokenMatches = css.matchAll(/var\(--([^)]+)\)/g);
      for (const m of tokenMatches) {
        if (!tokensUsed.includes(m[1])) {
          tokensUsed.push(m[1]);
        }
      }
    }

    return { name, propsBlock, variants, hasTest, hasStory, hasCss, tokensUsed };
  });

  // Gera o markdown
  let md = `# Components\n\n`;
  md += `## Available Components (${components.length})\n\n`;
  md += `> Auto-generated by sync-skill.mjs — do NOT edit manually.\n`;
  md += `> Last updated: ${new Date().toISOString().split('T')[0]}\n\n`;

  for (const comp of components) {
    md += `### ${comp.name}\n\n`;
    md += `**Import:** \`import { ${comp.name} } from '@pedrohenriquevalentim/olist-ds';\`\n\n`;
    md += `**Files:** `;
    md += `tsx ✅ `;
    md += comp.hasCss ? `css ✅ ` : `css ❌ `;
    md += comp.hasTest ? `test ✅ ` : `test ❌ `;
    md += comp.hasStory ? `story ✅` : `story ❌`;
    md += `\n\n`;

    md += `**Props:**\n\`\`\`tsx\n${comp.propsBlock}\n\`\`\`\n\n`;

    if (comp.tokensUsed.length > 0) {
      md += `**Tokens used:** `;
      md += comp.tokensUsed.slice(0, 15).map(t => `\`--${t}\``).join(', ');
      if (comp.tokensUsed.length > 15) md += ` (+${comp.tokensUsed.length - 15} more)`;
      md += `\n\n`;
    }

    md += `---\n\n`;
  }

  // Adiciona seção de componentes planejados
  md += `## Component Creation Rules\n\n`;
  md += `When building a new component:\n\n`;
  md += `1. Create in \`src/components/ComponentName/\` with all files (tsx, css, test, stories, index)\n`;
  md += `2. Use ONLY tokens from \`src/generated/variables.css\`\n`;
  md += `3. Export with named export (not default)\n`;
  md += `4. Props typed with \`interface\`\n`;
  md += `5. Include all states: default, hover, focus, active, disabled\n`;
  md += `6. Add ARIA attributes for accessibility\n`;
  md += `7. Use CSS Modules (\`.module.css\`)\n`;
  md += `8. After creation, run \`npm run build\` to update this skill automatically\n`;

  writeFileSync(join(SKILL_DIR, 'references', 'COMPONENTS.md'), md);
  console.log(`  ✅ COMPONENTS.md — ${components.length} components`);

  return components;
}

// ─── 2. Atualiza SOURCE_MAP.md ────────────────────────────

function syncSourceMap(components) {
  let md = `# Source Map\n\n`;
  md += `> Auto-generated by sync-skill.mjs — do NOT edit manually.\n`;
  md += `> Last updated: ${new Date().toISOString().split('T')[0]}\n\n`;

  md += `## Token Sources\n\n`;
  md += `| What | File path |\n|---|---|\n`;
  md += `| Raw tokens from Figma | \`src/tokens/base.json\` |\n`;
  md += `| CSS Custom Properties | \`src/generated/variables.css\` |\n`;
  md += `| JS token values | \`src/generated/tokens.js\` |\n`;
  md += `| Style Dictionary config | \`config.mjs\` |\n\n`;

  md += `## Component Files\n\n`;
  md += `| Component | Source | Styles | Tests | Stories |\n`;
  md += `|---|---|---|---|---|\n`;

  for (const comp of components) {
    const base = `src/components/${comp.name}`;
    md += `| ${comp.name} `;
    md += `| \`${base}/${comp.name}.tsx\` `;
    md += comp.hasCss ? `| \`${comp.name}.module.css\` ` : `| ❌ `;
    md += comp.hasTest ? `| \`${comp.name}.test.tsx\` ` : `| ❌ `;
    md += comp.hasStory ? `| \`${comp.name}.stories.tsx\` ` : `| ❌ `;
    md += `|\n`;
  }

  md += `\n## Auto-generated Files\n\n`;
  md += `| File | Generated by |\n|---|---|\n`;
  md += `| \`src/index.ts\` | \`scripts/generate-index.mjs\` |\n`;
  md += `| \`src/catalog.ts\` | \`scripts/generate-index.mjs\` |\n`;
  md += `| \`src/generated/variables.css\` | \`config.mjs\` |\n`;
  md += `| \`src/generated/tokens.js\` | \`config.mjs\` |\n`;
  md += `| \`.claude/skills/olist-ds-skill/references/COMPONENTS.md\` | \`scripts/sync-skill.mjs\` |\n`;
  md += `| \`.claude/skills/olist-ds-skill/references/SOURCE_MAP.md\` | \`scripts/sync-skill.mjs\` |\n`;

  md += `\n## Configuration Files\n\n`;
  md += `| File | Purpose |\n|---|---|\n`;
  md += `| \`config.mjs\` | Style Dictionary + custom transforms |\n`;
  md += `| \`tsconfig.json\` | TypeScript (rootDir: ./src, outDir: ./dist) |\n`;
  md += `| \`vite.config.ts\` | Vite + Vitest |\n`;
  md += `| \`package.json\` | Scripts, deps, NPM config |\n`;
  md += `| \`CLAUDE.md\` | Instructions for Claude Code |\n`;
  md += `| \`DESIGN.md\` | Google Labs design spec |\n`;

  writeFileSync(join(SKILL_DIR, 'references', 'SOURCE_MAP.md'), md);
  console.log(`  ✅ SOURCE_MAP.md — ${components.length} components mapped`);
}

// ─── 3. Atualiza OLIST_DS_OVERVIEW.md (lista de componentes) ─

function syncOverview(components) {
  const overviewPath = join(SKILL_DIR, 'references', 'OLIST_DS_OVERVIEW.md');
  let md = readFileSync(overviewPath, 'utf-8');

  // Substitui a lista de componentes existentes
  const componentList = components.map(c => `- **${c.name}**`).join('\n');
  const marker = '### Existing Components';
  const markerEnd = 'For full component API';

  const startIdx = md.indexOf(marker);
  const endIdx = md.indexOf(markerEnd);

  if (startIdx !== -1 && endIdx !== -1) {
    const before = md.substring(0, startIdx);
    const after = md.substring(endIdx);

    md = before;
    md += `### Existing Components\n\n`;
    md += `Before creating ANY new element, check if one of these exists (${components.length} total):\n\n`;
    md += componentList + '\n\n';
    md += after;

    writeFileSync(overviewPath, md);
    console.log(`  ✅ OLIST_DS_OVERVIEW.md — component list updated`);
  }
}

// ─── 4. Gera pacote .skill para upload no Claude.ai ───────

function packageForClaudeAI() {
  // Copia skill para outputs para fácil acesso
  const files = [];
  function walk(dir) {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else {
        files.push(full);
      }
    }
  }
  walk(SKILL_DIR);
  console.log(`  ✅ Skill package ready (${files.length} files)`);
}

// ─── EXECUÇÃO ─────────────────────────────────────────────

console.log('\n🔄 Syncing skill with design system...\n');

const components = syncComponents();
syncSourceMap(components);
syncOverview(components);
packageForClaudeAI();

console.log(`\n✅ Skill synced! ${components.length} components documented.`);
console.log(`   Upload .claude/skills/olist-ds-skill/ to Claude.ai to update.\n`);